name: Deploy to nasgio server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest and reload Caddy
        run: |
          cd /var/www/html
          git pull origin main
          sudo systemctl reload caddy